///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ContactUs {
/*
{
  "user": "66742a231bda099a9e8498de",
  "title": "jhkjasd",
  "description": "raissaaxase",
  "status": "PENDING",
  "_id": "669a30007836ea6dd01154c6",
  "createdAt": "2024-07-19T09:21:04.689Z",
  "updatedAt": "2024-07-19T09:21:04.689Z",
  "__v": 0
}
*/

  String? user;
  String? title;
  String? description;
  String? status;
  String? Id;
  String? createdAt;
  String? updatedAt;
  int? V;

  ContactUs({
    this.user,
    this.title,
    this.description,
    this.status,
    this.Id,
    this.createdAt,
    this.updatedAt,
    this.V,
  });
  ContactUs.fromJson(Map<String, dynamic> json) {
    user = json['user']?.toString();
    title = json['title']?.toString();
    description = json['description']?.toString();
    status = json['status']?.toString();
    Id = json['_id']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    V = json['__v']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['user'] = user;
    data['title'] = title;
    data['description'] = description;
    data['status'] = status;
    data['_id'] = Id;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['__v'] = V;
    return data;
  }
}
