///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class FetchCommunityPostDataCreatedBy {
/*
{
  "_id": "66742a231bda099a9e8498de",
  "email": "rohit.deshmukh@ideausher.com",
  "name": "Rohit Deshmukh",
  "userId": "100000"
}
*/

  String? Id;
  String? email;
  String? name;
  String? userId;

  FetchCommunityPostDataCreatedBy({
    this.Id,
    this.email,
    this.name,
    this.userId,
  });
  FetchCommunityPostDataCreatedBy.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    email = json['email']?.toString();
    name = json['name']?.toString();
    userId = json['userId']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = Id;
    data['email'] = email;
    data['name'] = name;
    data['userId'] = userId;
    return data;
  }
}

class FetchCommunityPostDataPostMedia {
/*
{
  "key": "image1",
  "url": "http://example.com/images/car-crash.jpg"
}
*/

  String? key;
  String? url;

  FetchCommunityPostDataPostMedia({
    this.key,
    this.url,
  });
  FetchCommunityPostDataPostMedia.fromJson(Map<String, dynamic> json) {
    key = json['key']?.toString();
    url = json['url']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['key'] = key;
    data['url'] = url;
    return data;
  }
}

class FetchCommunityPostDataLocation {
/*
{
  "coordinates": [
    -74.005974
  ],
  "addressLine": "123 Main St, New York, NY 10001",
  "type": "Point"
}
*/

  List<double?>? coordinates;
  String? addressLine;
  String? type;

  FetchCommunityPostDataLocation({
    this.coordinates,
    this.addressLine,
    this.type,
  });
  FetchCommunityPostDataLocation.fromJson(Map<String, dynamic> json) {
    if (json['coordinates'] != null) {
      final v = json['coordinates'];
      final arr0 = <double>[];
      v.forEach((v) {
        arr0.add(v.toDouble());
      });
      coordinates = arr0;
    }
    addressLine = json['addressLine']?.toString();
    type = json['type']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (coordinates != null) {
      final v = coordinates;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v);
      }
      data['coordinates'] = arr0;
    }
    data['addressLine'] = addressLine;
    data['type'] = type;
    return data;
  }
}

class FetchCommunityPostData {
/*
{
  "location": {
    "coordinates": [
      -74.005974
    ],
    "addressLine": "123 Main St, New York, NY 10001",
    "type": "Point"
  },
  "_id": "669a33ad7836ea6dd01154e2",
  "typeOfIncident": "Car crash",
  "description": "A car crash occurred at the intersection causing heavy traffic.11111111111111111",
  "postMedia": [
    {
      "key": "image1",
      "url": "http://example.com/images/car-crash.jpg"
    }
  ],
  "createdBy": {
    "_id": "66742a231bda099a9e8498de",
    "email": "rohit.deshmukh@ideausher.com",
    "name": "Rohit Deshmukh",
    "userId": "100000"
  },
  "isDeleted": false,
  "createdAt": "2024-07-19T09:36:45.966Z",
  "updatedAt": "2024-07-19T09:36:45.966Z",
  "__v": 0
}
*/

  FetchCommunityPostDataLocation? location;
  String? Id;
  String? typeOfIncident;
  String? description;
  List<FetchCommunityPostDataPostMedia?>? postMedia;
  FetchCommunityPostDataCreatedBy? createdBy;
  bool? isDeleted;
  String? createdAt;
  String? updatedAt;
  int? V;

  FetchCommunityPostData({
    this.location,
    this.Id,
    this.typeOfIncident,
    this.description,
    this.postMedia,
    this.createdBy,
    this.isDeleted,
    this.createdAt,
    this.updatedAt,
    this.V,
  });
  FetchCommunityPostData.fromJson(Map<String, dynamic> json) {
    location = (json['location'] != null)
        ? FetchCommunityPostDataLocation.fromJson(json['location'])
        : null;
    Id = json['_id']?.toString();
    typeOfIncident = json['typeOfIncident']?.toString();
    description = json['description']?.toString();
    if (json['postMedia'] != null) {
      final v = json['postMedia'];
      final arr0 = <FetchCommunityPostDataPostMedia>[];
      v.forEach((v) {
        arr0.add(FetchCommunityPostDataPostMedia.fromJson(v));
      });
      postMedia = arr0;
    }
    createdBy = (json['createdBy'] != null)
        ? FetchCommunityPostDataCreatedBy.fromJson(json['createdBy'])
        : null;
    isDeleted = json['isDeleted'];
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    V = json['__v']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (location != null) {
      data['location'] = location!.toJson();
    }
    data['_id'] = Id;
    data['typeOfIncident'] = typeOfIncident;
    data['description'] = description;
    if (postMedia != null) {
      final v = postMedia;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['postMedia'] = arr0;
    }
    if (createdBy != null) {
      data['createdBy'] = createdBy!.toJson();
    }
    data['isDeleted'] = isDeleted;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['__v'] = V;
    return data;
  }
}

class FetchCommunityPost {
/*
{
  "data": [
    {
      "location": {
        "coordinates": [
          -74.005974
        ],
        "addressLine": "123 Main St, New York, NY 10001",
        "type": "Point"
      },
      "_id": "669a33ad7836ea6dd01154e2",
      "typeOfIncident": "Car crash",
      "description": "A car crash occurred at the intersection causing heavy traffic.11111111111111111",
      "postMedia": [
        {
          "key": "image1",
          "url": "http://example.com/images/car-crash.jpg"
        }
      ],
      "createdBy": {
        "_id": "66742a231bda099a9e8498de",
        "email": "rohit.deshmukh@ideausher.com",
        "name": "Rohit Deshmukh",
        "userId": "100000"
      },
      "isDeleted": false,
      "createdAt": "2024-07-19T09:36:45.966Z",
      "updatedAt": "2024-07-19T09:36:45.966Z",
      "__v": 0
    }
  ]
}
*/

  List<FetchCommunityPostData?>? data;

  FetchCommunityPost({
    this.data,
  });
  FetchCommunityPost.fromJson(Map<String, dynamic> json) {
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <FetchCommunityPostData>[];
      v.forEach((v) {
        arr0.add(FetchCommunityPostData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
