///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SearchLocationHistoryDataResultsLocation {
/*
{
  "type": "Point",
  "coordinates": [
    -73.935242
  ],
  "addressLine": "123 Main Street, New York, NY"
}
*/

  String? type;
  List<double?>? coordinates;
  String? addressLine;

  SearchLocationHistoryDataResultsLocation({
    this.type,
    this.coordinates,
    this.addressLine,
  });
  SearchLocationHistoryDataResultsLocation.fromJson(Map<String, dynamic> json) {
    type = json['type']?.toString();
    if (json['coordinates'] != null) {
      final v = json['coordinates'];
      final arr0 = <double>[];
      v.forEach((v) {
        arr0.add(v.toDouble());
      });
      coordinates = arr0;
    }
    addressLine = json['addressLine']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['type'] = type;
    if (coordinates != null) {
      final v = coordinates;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['coordinates'] = arr0;
    }
    data['addressLine'] = addressLine;
    return data;
  }
}

class SearchLocationHistoryDataResults {
/*
{
  "_id": "66fa9e14c746cf482f274cf5",
  "user": "6682724beeaf4b71f48bd68d",
  "type": "SAVED",
  "title": "My Favorite Spot",
  "location": {
    "type": "Point",
    "coordinates": [
      -73.935242
    ],
    "addressLine": "123 Main Street, New York, NY"
  },
  "createdAt": "2024-09-30T12:48:20.042Z",
  "updatedAt": "2024-09-30T12:48:20.042Z",
  "__v": 0
}
*/

  String? Id;
  String? user;
  String? type;
  String? title;
  String? placeId;
  SearchLocationHistoryDataResultsLocation? location;
  String? createdAt;
  String? updatedAt;
  int? V;

  SearchLocationHistoryDataResults({
    this.Id,
    this.user,
    this.type,
    this.title,
    this.location,
    this.createdAt,
    this.updatedAt,
    this.placeId,
    this.V,
  });
  SearchLocationHistoryDataResults.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    user = json['user']?.toString();
    type = json['type']?.toString();
    placeId = json['placeId']?.toString();
    title = json['title']?.toString();
    location = (json['location'] != null)
        ? SearchLocationHistoryDataResultsLocation.fromJson(json['location'])
        : null;
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    V = json['__v']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = Id;
    data['user'] = user;
    data['type'] = type;
    data['title'] = title;
    data['placeId'] = placeId;
    if (location != null) {
      data['location'] = location!.toJson();
    }
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['__v'] = V;
    return data;
  }
}

class SearchLocationHistoryData {
/*
{
  "page": 1,
  "limit": 10,
  "results": [
    {
      "_id": "66fa9e14c746cf482f274cf5",
      "user": "6682724beeaf4b71f48bd68d",
      "type": "SAVED",
      "title": "My Favorite Spot",
      "location": {
        "type": "Point",
        "coordinates": [
          -73.935242
        ],
        "addressLine": "123 Main Street, New York, NY"
      },
      "createdAt": "2024-09-30T12:48:20.042Z",
      "updatedAt": "2024-09-30T12:48:20.042Z",
      "__v": 0
    }
  ],
  "totalPages": 1,
  "totalResults": 2
}
*/

  int? page;
  int? limit;
  List<SearchLocationHistoryDataResults?>? results;
  int? totalPages;
  int? totalResults;

  SearchLocationHistoryData({
    this.page,
    this.limit,
    this.results,
    this.totalPages,
    this.totalResults,
  });
  SearchLocationHistoryData.fromJson(Map<String, dynamic> json) {
    page = json['page']?.toInt();
    limit = json['limit']?.toInt();
    if (json['results'] != null) {
      final v = json['results'];
      final arr0 = <SearchLocationHistoryDataResults>[];
      v.forEach((v) {
        arr0.add(SearchLocationHistoryDataResults.fromJson(v));
      });
      results = arr0;
    }
    totalPages = json['totalPages']?.toInt();
    totalResults = json['totalResults']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['page'] = page;
    data['limit'] = limit;
    if (results != null) {
      final v = results;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['results'] = arr0;
    }
    data['totalPages'] = totalPages;
    data['totalResults'] = totalResults;
    return data;
  }
}

class SearchLocationHistory {
/*
{
  "data": {
    "page": 1,
    "limit": 10,
    "results": [
      {
        "_id": "66fa9e14c746cf482f274cf5",
        "user": "6682724beeaf4b71f48bd68d",
        "type": "SAVED",
        "title": "My Favorite Spot",
        "location": {
          "type": "Point",
          "coordinates": [
            -73.935242
          ],
          "addressLine": "123 Main Street, New York, NY"
        },
        "createdAt": "2024-09-30T12:48:20.042Z",
        "updatedAt": "2024-09-30T12:48:20.042Z",
        "__v": 0
      }
    ],
    "totalPages": 1,
    "totalResults": 2
  }
}
*/

  SearchLocationHistoryData? data;

  SearchLocationHistory({
    this.data,
  });
  SearchLocationHistory.fromJson(Map<String, dynamic> json) {
    data = (json['data'] != null)
        ? SearchLocationHistoryData.fromJson(json['data'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
