///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class GetRoutesDataInstructions {
/*
{
  "street_ref": "NH48",
  "distance": 100.399,
  "heading": 8.53,
  "sign": 0,
  "interval": [
    0
  ],
  "text": "Fortsätt in på Western Express Highway",
  "time": 7530,
  "street_name": "Western Express Highway"
}
*/

  String? streetRef;
  double? distance;
  double? heading;
  int? sign;
  List<int?>? interval;
  String? text;
  int? time;
  String? streetName;

  GetRoutesDataInstructions({
    this.streetRef,
    this.distance,
    this.heading,
    this.sign,
    this.interval,
    this.text,
    this.time,
    this.streetName,
  });
  GetRoutesDataInstructions.fromJson(Map<String, dynamic> json) {
    streetRef = json['street_ref']?.toString();
    distance = json['distance']?.toDouble();
    heading = json['heading']?.toDouble();
    sign = json['sign']?.toInt();
    if (json['interval'] != null) {
      final v = json['interval'];
      final arr0 = <int>[];
      v.forEach((v) {
        arr0.add(v.toInt());
      });
      interval = arr0;
    }
    text = json['text']?.toString();
    time = json['time']?.toInt();
    streetName = json['street_name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['street_ref'] = streetRef;
    data['distance'] = distance;
    data['heading'] = heading;
    data['sign'] = sign;
    if (interval != null) {
      final v = interval;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['interval'] = arr0;
    }
    data['text'] = text;
    data['time'] = time;
    data['street_name'] = streetName;
    return data;
  }
}

class GetRoutesData {
/*
{
  "distance": 12467.771,
  "time": 1052471,
  "instructions": [
    {
      "street_ref": "NH48",
      "distance": 100.399,
      "heading": 8.53,
      "sign": 0,
      "interval": [
        0
      ],
      "text": "Fortsätt in på Western Express Highway",
      "time": 7530,
      "street_name": "Western Express Highway"
    }
  ],
  "points": "ayltBsev{LqD[IDsAIe@AmBM_D[mEU{AOZ}@xALxD\\~E^zATdAJNJzJ|@fE\\lIh@~@Fr@BhAArEEtBCjGGvI?fK@~C?dBEbCWb@KdEoAfAYpA[tEeA`HeB|EiAvAa@`E_AnEcA~HuBbHaBpBm@jEgAxBe@lAUdBWzAKxACjB?dBDbAHrAN|@RdAVn@TjBv@hAj@vA|@dAv@pF`FdR~QlB`B\\^h@d@f@\\`@TTHZPd@N|@TvATjC^d@D|ARjMpAxFv@|Ej@nAZRJvB|@`A^dFhCd@Rx@P~@FnA@zDAhC@fC?|IK|EC~BAhEF~C@jECjI@fDEvECzAMhAKZEp@OnEiAfEw@vBKfA?nCLlNt@|CPxETzUtAjN`AhJr@jN|@~PtArEf@~CVbDH|BH`Lf@~BKhFVpLd@GfAyEQeJ_@q@]_CMi@r@cFW"
}
*/

  double? distance;
  int? time;
  List<GetRoutesDataInstructions?>? instructions;
  String? points;

  GetRoutesData({
    this.distance,
    this.time,
    this.instructions,
    this.points,
  });
  GetRoutesData.fromJson(Map<String, dynamic> json) {
    distance = json['distance']?.toDouble();
    time = json['time']?.toInt();
    if (json['instructions'] != null) {
      final v = json['instructions'];
      final arr0 = <GetRoutesDataInstructions>[];
      v.forEach((v) {
        arr0.add(GetRoutesDataInstructions.fromJson(v));
      });
      instructions = arr0;
    }
    points = json['points']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['distance'] = distance;
    data['time'] = time;
    if (instructions != null) {
      final v = instructions;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['instructions'] = arr0;
    }
    data['points'] = points;
    return data;
  }
}

class GetRoutes {
/*
{
  "data": {
    "distance": 12467.771,
    "time": 1052471,
    "instructions": [
      {
        "street_ref": "NH48",
        "distance": 100.399,
        "heading": 8.53,
        "sign": 0,
        "interval": [
          0
        ],
        "text": "Fortsätt in på Western Express Highway",
        "time": 7530,
        "street_name": "Western Express Highway"
      }
    ],
    "points": "ayltBsev{LqD[IDsAIe@AmBM_D[mEU{AOZ}@xALxD\\~E^zATdAJNJzJ|@fE\\lIh@~@Fr@BhAArEEtBCjGGvI?fK@~C?dBEbCWb@KdEoAfAYpA[tEeA`HeB|EiAvAa@`E_AnEcA~HuBbHaBpBm@jEgAxBe@lAUdBWzAKxACjB?dBDbAHrAN|@RdAVn@TjBv@hAj@vA|@dAv@pF`FdR~QlB`B\\^h@d@f@\\`@TTHZPd@N|@TvATjC^d@D|ARjMpAxFv@|Ej@nAZRJvB|@`A^dFhCd@Rx@P~@FnA@zDAhC@fC?|IK|EC~BAhEF~C@jECjI@fDEvECzAMhAKZEp@OnEiAfEw@vBKfA?nCLlNt@|CPxETzUtAjN`AhJr@jN|@~PtArEf@~CVbDH|BH`Lf@~BKhFVpLd@GfAyEQeJ_@q@]_CMi@r@cFW"
  }
}
*/

  GetRoutesData? data;

  GetRoutes({
    this.data,
  });
  GetRoutes.fromJson(Map<String, dynamic> json) {
    data = (json['data'] != null) ? GetRoutesData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['data'] = this.data!.toJson();
    return data;
  }
}
