///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class postSaveLocationDataLocation {
/*
{
  "type": "Point",
  "coordinates": [
    -73.935242
  ],
  "addressLine": "123 Main Street, New York, NY"
}
*/

  String? type;
  List<double?>? coordinates;
  String? addressLine;

  postSaveLocationDataLocation({
    this.type,
    this.coordinates,
    this.addressLine,
  });
  postSaveLocationDataLocation.fromJson(Map<String, dynamic> json) {
    type = json['type']?.toString();
    if (json['coordinates'] != null) {
      final v = json['coordinates'];
      final arr0 = <double>[];
      v.forEach((v) {
        arr0.add(v.toDouble());
      });
      coordinates = arr0;
    }
    addressLine = json['addressLine']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['type'] = type;
    if (coordinates != null) {
      final v = coordinates;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['coordinates'] = arr0;
    }
    data['addressLine'] = addressLine;
    return data;
  }
}

class postSaveLocationData {
/*
{
  "user": "6682724beeaf4b71f48bd68d",
  "type": "HISTORY",
  "title": "My Favorite Spot",
  "location": {
    "type": "Point",
    "coordinates": [
      -73.935242
    ],
    "addressLine": "123 Main Street, New York, NY"
  },
  "_id": "66fa9d81b3919110d3fd5f75",
  "createdAt": "2024-09-30T12:45:53.748Z",
  "updatedAt": "2024-09-30T12:45:53.748Z",
  "v": 0
}
*/

  String? user;
  String? type;
  String? title;
  postSaveLocationDataLocation? location;
  String? Id;
  String? createdAt;
  String? updatedAt;
  int? v;

  postSaveLocationData({
    this.user,
    this.type,
    this.title,
    this.location,
    this.Id,
    this.createdAt,
    this.updatedAt,
    this.v,
  });
  postSaveLocationData.fromJson(Map<String, dynamic> json) {
    user = json['user']?.toString();
    type = json['type']?.toString();
    title = json['title']?.toString();
    location = (json['location'] != null)
        ? postSaveLocationDataLocation.fromJson(json['location'])
        : null;
    Id = json['_id']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    v = json['v']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['user'] = user;
    data['type'] = type;
    data['title'] = title;
    if (location != null) {
      data['location'] = location!.toJson();
    }
    data['_id'] = Id;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['v'] = v;
    return data;
  }
}

class postSaveLocation {
/*
{
  "data": {
    "user": "6682724beeaf4b71f48bd68d",
    "type": "HISTORY",
    "title": "My Favorite Spot",
    "location": {
      "type": "Point",
      "coordinates": [
        -73.935242
      ],
      "addressLine": "123 Main Street, New York, NY"
    },
    "_id": "66fa9d81b3919110d3fd5f75",
    "createdAt": "2024-09-30T12:45:53.748Z",
    "updatedAt": "2024-09-30T12:45:53.748Z",
    "v": 0
  }
}
*/

  postSaveLocationData? data;

  postSaveLocation({
    this.data,
  });
  postSaveLocation.fromJson(Map<String, dynamic> json) {
    data = (json['data'] != null)
        ? postSaveLocationData.fromJson(json['data'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
