///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CreateCommunityPostPostMedia {
/*
{
  "key": "image1",
  "url": "http://example.com/images/car-crash.jpg"
}
*/

  String? key;
  String? url;

  CreateCommunityPostPostMedia({
    this.key,
    this.url,
  });
  CreateCommunityPostPostMedia.fromJson(Map<String, dynamic> json) {
    key = json['key']?.toString();
    url = json['url']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['key'] = key;
    data['url'] = url;
    return data;
  }
}

class CreateCommunityPostLocation {
/*
{
  "type": "Point",
  "coordinates": [
    -74.005974
  ],
  "addressLine": "123 Main St, New York, NY 10001"
}
*/

  String? type;
  List<double?>? coordinates;
  String? addressLine;

  CreateCommunityPostLocation({
    this.type,
    this.coordinates,
    this.addressLine,
  });
  CreateCommunityPostLocation.fromJson(Map<String, dynamic> json) {
    type = json['type']?.toString();
    if (json['coordinates'] != null) {
      final v = json['coordinates'];
      final arr0 = <double>[];
      v.forEach((v) {
        arr0.add(v.toDouble());
      });
      coordinates = arr0;
    }
    addressLine = json['addressLine']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['type'] = type;
    if (coordinates != null) {
      final v = coordinates;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['coordinates'] = arr0;
    }
    data['addressLine'] = addressLine;
    return data;
  }
}

class CreateCommunityPost {
/*
{
  "typeOfIncident": "Car crash",
  "location": {
    "type": "Point",
    "coordinates": [
      -74.005974
    ],
    "addressLine": "123 Main St, New York, NY 10001"
  },
  "description": "A car crash occurred at the intersection causing heavy traffic.11111111111111111",
  "postMedia": [
    {
      "key": "image1",
      "url": "http://example.com/images/car-crash.jpg"
    }
  ]
}
*/

  String? typeOfIncident;
  CreateCommunityPostLocation? location;
  String? description;
  List<CreateCommunityPostPostMedia?>? postMedia;

  CreateCommunityPost({
    this.typeOfIncident,
    this.location,
    this.description,
    this.postMedia,
  });
  CreateCommunityPost.fromJson(Map<String, dynamic> json) {
    typeOfIncident = json['typeOfIncident']?.toString();
    location = (json['location'] != null)
        ? CreateCommunityPostLocation.fromJson(json['location'])
        : null;
    description = json['description']?.toString();
    if (json['postMedia'] != null) {
      final v = json['postMedia'];
      final arr0 = <CreateCommunityPostPostMedia>[];
      v.forEach((v) {
        arr0.add(CreateCommunityPostPostMedia.fromJson(v));
      });
      postMedia = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['typeOfIncident'] = typeOfIncident;
    if (location != null) {
      data['location'] = location!.toJson();
    }
    data['description'] = description;
    if (postMedia != null) {
      final v = postMedia;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['postMedia'] = arr0;
    }
    return data;
  }
}
