///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SaveRoutesData {
/*
{
  "user": "66742a231bda099a9e8498de",
  "points": "smmtBsfu{L_BKmDIOfI~BZhBXvE|@hBFXDx@Xl@FGxBYvAIl@?^CV?h@Bf@\\CrAGzCMvDWrF[JOL_@Ac@HyARuAl@sCLq@BY@eAIwAU_AOk@U[UC]M[Ik@K_@AgAKSESMKOGOEw@lDYnAFbBNn@JbBZzBj@rCbAzC`AbCp@xBp@lAZFwC~BWlDo@QqBGwBHsBDo@FqCBkCCyBDSYqArUBN@f@Nl@CbCWb@KdEoAfAYpA[tEeA`HeB|EiAvAa@`GwAnCq@~Cs@~C{@bFiA~@WpBm@jEgAxBe@lAUbBUxAMnH@bAHrAN|@RdAVn@TjBv@hAj@vA|@dAv@pF`FnMjMn@XZHhDbDfA~@p@f@p@^p@X^JX[h@cALa@NHc@|@i@bAe@pAYp@Od@IZCn@D|B@pAKzDM|BIx@GVi@vCSGZmBPuATeDFgB@s@AgBq@Ag@DyB]I@EDAjAEJUTc@ZMHEF]hB",
  "instructions": [
    "Turn left at the next intersection"
  ],
  "time": 120,
  "distance": 5,
  "type": "OFFLINE",
  "_id": "66c83f88176f499be2fe19e0",
  "createdAt": "2024-08-23T07:51:36.574Z",
  "updatedAt": "2024-08-23T07:51:36.574Z",
  "__v": 0
}
*/

  String? user;
  String? points;
  List<String?>? instructions;
  int? time;
  int? distance;
  String? type;
  String? Id;
  String? createdAt;
  String? updatedAt;
  int? V;

  SaveRoutesData({
    this.user,
    this.points,
    this.instructions,
    this.time,
    this.distance,
    this.type,
    this.Id,
    this.createdAt,
    this.updatedAt,
    this.V,
  });
  SaveRoutesData.fromJson(Map<String, dynamic> json) {
    user = json['user']?.toString();
    points = json['points']?.toString();
    if (json['instructions'] != null) {
      final v = json['instructions'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      instructions = arr0;
    }
    time = json['time']?.toInt();
    distance = json['distance']?.toInt();
    type = json['type']?.toString();
    Id = json['_id']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    V = json['__v']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['user'] = user;
    data['points'] = points;
    if (instructions != null) {
      final v = instructions;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['instructions'] = arr0;
    }
    data['time'] = time;
    data['distance'] = distance;
    data['type'] = type;
    data['_id'] = Id;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['__v'] = V;
    return data;
  }
}

class SaveRoutes {
/*
{
  "data": {
    "user": "66742a231bda099a9e8498de",
    "points": "smmtBsfu{L_BKmDIOfI~BZhBXvE|@hBFXDx@Xl@FGxBYvAIl@?^CV?h@Bf@\\CrAGzCMvDWrF[JOL_@Ac@HyARuAl@sCLq@BY@eAIwAU_AOk@U[UC]M[Ik@K_@AgAKSESMKOGOEw@lDYnAFbBNn@JbBZzBj@rCbAzC`AbCp@xBp@lAZFwC~BWlDo@QqBGwBHsBDo@FqCBkCCyBDSYqArUBN@f@Nl@CbCWb@KdEoAfAYpA[tEeA`HeB|EiAvAa@`GwAnCq@~Cs@~C{@bFiA~@WpBm@jEgAxBe@lAUbBUxAMnH@bAHrAN|@RdAVn@TjBv@hAj@vA|@dAv@pF`FnMjMn@XZHhDbDfA~@p@f@p@^p@X^JX[h@cALa@NHc@|@i@bAe@pAYp@Od@IZCn@D|B@pAKzDM|BIx@GVi@vCSGZmBPuATeDFgB@s@AgBq@Ag@DyB]I@EDAjAEJUTc@ZMHEF]hB",
    "instructions": [
      "Turn left at the next intersection"
    ],
    "time": 120,
    "distance": 5,
    "type": "OFFLINE",
    "_id": "66c83f88176f499be2fe19e0",
    "createdAt": "2024-08-23T07:51:36.574Z",
    "updatedAt": "2024-08-23T07:51:36.574Z",
    "__v": 0
  }
}
*/

  SaveRoutesData? data;

  SaveRoutes({
    this.data,
  });
  SaveRoutes.fromJson(Map<String, dynamic> json) {
    data =
        (json['data'] != null) ? SaveRoutesData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['data'] = this.data!.toJson();
    return data;
  }
}
