///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SetProfileDetailsDataProfilePic {
/*
{
  "key": "public/uploads/b59c3bd7-4516-407c-8076-f1d222d5463c-images.png",
  "url": "https://moped-gps.s3.ap-south-1.amazonaws.com/public/uploads/9dc21e29-e932-480a-b033-931dbf99aafa-images.png",
  "_id": "66990af3dabac906e0b6c16a"
}
*/

  String? key;
  String? url;
  String? Id;

  SetProfileDetailsDataProfilePic({
    this.key,
    this.url,
    this.Id,
  });
  SetProfileDetailsDataProfilePic.fromJson(Map<String, dynamic> json) {
    key = json['key']?.toString();
    url = json['url']?.toString();
    Id = json['_id']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['key'] = key;
    data['url'] = url;
    data['_id'] = Id;
    return data;
  }
}

class SetProfileDetailsData {
/*
{
  "name": "john cena",
  "phone": "+919082060622",
  "email": "johncena@gmail.com",
  "role": "667414759da4b6240ff1c331",
  "profilePic": {
    "key": "public/uploads/b59c3bd7-4516-407c-8076-f1d222d5463c-images.png",
    "url": "https://moped-gps.s3.ap-south-1.amazonaws.com/public/uploads/9dc21e29-e932-480a-b033-931dbf99aafa-images.png",
    "_id": "66990af3dabac906e0b6c16a"
  },
  "isEmailVerified": true,
  "dob": "1997-05-10T00:00:00.000Z",
  "firebaseUid": "ukoLbHQ13TUD5kXMQVcNcAlIzIc2",
  "firebaseSignInProvider": "custom",
  "isTrailActivated": false,
  "trailStarted": true,
  "trialEnded": false,
  "isBlocked": false,
  "isDeleted": false,
  "_id": "66990af3dabac906e0b6c169",
  "createdAt": "2024-07-18T12:30:43.196Z",
  "updatedAt": "2024-07-18T12:30:43.196Z",
  "userId": "31974805",
  "__v": 0
}
*/

  String? name;
  String? phone;
  String? email;
  String? role;
  SetProfileDetailsDataProfilePic? profilePic;
  bool? isEmailVerified;
  String? dob;
  String? firebaseUid;
  String? firebaseSignInProvider;
  bool? isTrailActivated;
  bool? trailStarted;
  bool? trialEnded;
  bool? isBlocked;
  bool? isDeleted;
  String? Id;
  String? createdAt;
  String? updatedAt;
  String? userId;
  int? V;

  SetProfileDetailsData({
    this.name,
    this.phone,
    this.email,
    this.role,
    this.profilePic,
    this.isEmailVerified,
    this.dob,
    this.firebaseUid,
    this.firebaseSignInProvider,
    this.isTrailActivated,
    this.trailStarted,
    this.trialEnded,
    this.isBlocked,
    this.isDeleted,
    this.Id,
    this.createdAt,
    this.updatedAt,
    this.userId,
    this.V,
  });
  SetProfileDetailsData.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
    phone = json['phone']?.toString();
    email = json['email']?.toString();
    role = json['role']?.toString();
    profilePic = (json['profilePic'] != null)
        ? SetProfileDetailsDataProfilePic.fromJson(json['profilePic'])
        : null;
    isEmailVerified = json['isEmailVerified'];
    dob = json['dob']?.toString();
    firebaseUid = json['firebaseUid']?.toString();
    firebaseSignInProvider = json['firebaseSignInProvider']?.toString();
    isTrailActivated = json['isTrailActivated'];
    trailStarted = json['trailStarted'];
    trialEnded = json['trialEnded'];
    isBlocked = json['isBlocked'];
    isDeleted = json['isDeleted'];
    Id = json['_id']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    userId = json['userId']?.toString();
    V = json['__v']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['phone'] = phone;
    data['email'] = email;
    data['role'] = role;
    if (profilePic != null) {
      data['profilePic'] = profilePic!.toJson();
    }
    data['isEmailVerified'] = isEmailVerified;
    data['dob'] = dob;
    data['firebaseUid'] = firebaseUid;
    data['firebaseSignInProvider'] = firebaseSignInProvider;
    data['isTrailActivated'] = isTrailActivated;
    data['trailStarted'] = trailStarted;
    data['trialEnded'] = trialEnded;
    data['isBlocked'] = isBlocked;
    data['isDeleted'] = isDeleted;
    data['_id'] = Id;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['userId'] = userId;
    data['__v'] = V;
    return data;
  }
}

class SetProfileDetails {
/*
{
  "data": {
    "name": "john cena",
    "phone": "+919082060622",
    "email": "johncena@gmail.com",
    "role": "667414759da4b6240ff1c331",
    "profilePic": {
      "key": "public/uploads/b59c3bd7-4516-407c-8076-f1d222d5463c-images.png",
      "url": "https://moped-gps.s3.ap-south-1.amazonaws.com/public/uploads/9dc21e29-e932-480a-b033-931dbf99aafa-images.png",
      "_id": "66990af3dabac906e0b6c16a"
    },
    "isEmailVerified": true,
    "dob": "1997-05-10T00:00:00.000Z",
    "firebaseUid": "ukoLbHQ13TUD5kXMQVcNcAlIzIc2",
    "firebaseSignInProvider": "custom",
    "isTrailActivated": false,
    "trailStarted": true,
    "trialEnded": false,
    "isBlocked": false,
    "isDeleted": false,
    "_id": "66990af3dabac906e0b6c169",
    "createdAt": "2024-07-18T12:30:43.196Z",
    "updatedAt": "2024-07-18T12:30:43.196Z",
    "userId": "31974805",
    "__v": 0
  }
}
*/

  SetProfileDetailsData? data;

  SetProfileDetails({
    this.data,
  });
  SetProfileDetails.fromJson(Map<String, dynamic> json) {
    data = (json['data'] != null)
        ? SetProfileDetailsData.fromJson(json['data'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['data'] = this.data!.toJson();
    return data;
  }
}
