///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class UserDeatilsProfilePic {
/*
{
  "key": "public/uploads/b59c3bd7-4516-407c-8076-f1d222d5463c-images.png",
  "url": "https://moped-gps.s3.ap-south-1.amazonaws.com/public/uploads/9dc21e29-e932-480a-b033-931dbf99aafa-images.png",
  "_id": "667508c7a49088f1e8e60677"
}
*/

  String? key;
  String? url;
  String? Id;

  UserDeatilsProfilePic({
    this.key,
    this.url,
    this.Id,
  });
  UserDeatilsProfilePic.fromJson(Map<String, dynamic> json) {
    key = json['key']?.toString();
    url = json['url']?.toString();
    Id = json['_id']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['key'] = key;
    data['url'] = url;
    data['_id'] = Id;
    return data;
  }
}

class UserDeatilsRole {
/*
{
  "_id": "667414759da4b6240ff1c331",
  "name": "USER"
}
*/

  String? Id;
  String? name;

  UserDeatilsRole({
    this.Id,
    this.name,
  });
  UserDeatilsRole.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    name = json['name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = Id;
    data['name'] = name;
    return data;
  }
}

class UserDetails {
/*
{
  "_id": "66742a231bda099a9e8498de",
  "phone": "+918433516251",
  "role": {
    "_id": "667414759da4b6240ff1c331",
    "name": "USER"
  },
  "profilePic": {
    "key": "public/uploads/b59c3bd7-4516-407c-8076-f1d222d5463c-images.png",
    "url": "https://moped-gps.s3.ap-south-1.amazonaws.com/public/uploads/9dc21e29-e932-480a-b033-931dbf99aafa-images.png",
    "_id": "667508c7a49088f1e8e60677"
  },
  "isEmailVerified": true,
  "dob": "2023-05-20T14:00:00.000Z",
  "firebaseUid": "3cqvAsaQ6jMPMzpuP5hPOPON5t22",
  "firebaseSignInProvider": "custom",
  "isBlocked": false,
  "isDeleted": false,
  "createdAt": "2024-06-20T13:09:55.511Z",
  "updatedAt": "2024-07-08T18:30:01.890Z",
  "__v": 0,
  "email": "rohit.deshmukh@ideausher.com",
  "name": "Rohit Deshmukh",
  "isTrailActivated": false,
  "trailStarted": "2024-06-28T00:00:00.000Z",
  "trialEnded": "2024-07-08T18:30:01.722Z",
  "subscription": "667fda66fc437b3ffee895e9",
  "userId": "100000"
}
*/

  String? Id;
  String? phone;
  UserDeatilsRole? role;
  UserDeatilsProfilePic? profilePic;
  bool? isEmailVerified;
  String? dob;
  String? firebaseUid;
  String? firebaseSignInProvider;
  bool? isBlocked;
  bool? isDeleted;
  String? createdAt;
  String? updatedAt;
  int? V;
  String? email;
  String? name;
  bool? isTrailActivated;
  String? trailStarted;
  String? trialEnded;
  String? subscription;
  String? userId;

  UserDetails({
    this.Id,
    this.phone,
    this.role,
    this.profilePic,
    this.isEmailVerified,
    this.dob,
    this.firebaseUid,
    this.firebaseSignInProvider,
    this.isBlocked,
    this.isDeleted,
    this.createdAt,
    this.updatedAt,
    this.V,
    this.email,
    this.name,
    this.isTrailActivated,
    this.trailStarted,
    this.trialEnded,
    this.subscription,
    this.userId,
  });
  UserDetails.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    phone = json['phone']?.toString();
    role =
        (json['role'] != null) ? UserDeatilsRole.fromJson(json['role']) : null;
    profilePic = (json['profilePic'] != null)
        ? UserDeatilsProfilePic.fromJson(json['profilePic'])
        : null;
    isEmailVerified = json['isEmailVerified'];
    dob = json['dob']?.toString();
    firebaseUid = json['firebaseUid']?.toString();
    firebaseSignInProvider = json['firebaseSignInProvider']?.toString();
    isBlocked = json['isBlocked'];
    isDeleted = json['isDeleted'];
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    V = json['__v']?.toInt();
    email = json['email']?.toString();
    name = json['name']?.toString();
    isTrailActivated = json['isTrailActivated'];
    trailStarted = json['trailStarted']?.toString();
    trialEnded = json['trialEnded']?.toString();
    subscription = json['subscription']?.toString();
    userId = json['userId']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = Id;
    data['phone'] = phone;
    if (role != null) {
      data['role'] = role!.toJson();
    }
    if (profilePic != null) {
      data['profilePic'] = profilePic!.toJson();
    }
    data['isEmailVerified'] = isEmailVerified;
    data['dob'] = dob;
    data['firebaseUid'] = firebaseUid;
    data['firebaseSignInProvider'] = firebaseSignInProvider;
    data['isBlocked'] = isBlocked;
    data['isDeleted'] = isDeleted;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['__v'] = V;
    data['email'] = email;
    data['name'] = name;
    data['isTrailActivated'] = isTrailActivated;
    data['trailStarted'] = trailStarted;
    data['trialEnded'] = trialEnded;
    data['subscription'] = subscription;
    data['userId'] = userId;
    return data;
  }
}
