// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4f44oJo3SsKMGlSJnICjCQ_1JCJRbkhE',
    appId: '1:734724432257:web:0f54ae235b1f91760d0880',
    messagingSenderId: '734724432257',
    projectId: 'mopedgps-e5c51',
    authDomain: 'mopedgps-e5c51.firebaseapp.com',
    storageBucket: 'mopedgps-e5c51.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6asitgM8tbYW0r3QaiLtcYgDvpplkA_E',
    appId: '1:734724432257:android:aabc861ab18de3ea0d0880',
    messagingSenderId: '734724432257',
    projectId: 'mopedgps-e5c51',
    storageBucket: 'mopedgps-e5c51.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqjdtoQ89o8LYuIhf8eaQttMikWQeJkY8',
    appId: '1:734724432257:ios:621666904d6fa1ba0d0880',
    messagingSenderId: '734724432257',
    projectId: 'mopedgps-e5c51',
    storageBucket: 'mopedgps-e5c51.firebasestorage.app',
    iosBundleId: 'iu.mopedsafe.com.mopedsafe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqjdtoQ89o8LYuIhf8eaQttMikWQeJkY8',
    appId: '1:734724432257:ios:d5ac4d659bc269e50d0880',
    messagingSenderId: '734724432257',
    projectId: 'mopedgps-e5c51',
    storageBucket: 'mopedgps-e5c51.firebasestorage.app',
    iosBundleId: 'iu.mopedsafe.com.mopedsafe.RunnerTests',
  );
}
