// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM7Zhw0ZyCAGgRss880QfXMd-MNRiNZyw',
    appId: '1:4063681274:web:91efd2c60dbd69521d8743',
    messagingSenderId: '4063681274',
    projectId: 'iumopedsafe',
    authDomain: 'iumopedsafe.firebaseapp.com',
    databaseURL: 'https://iumopedsafe-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iumopedsafe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYwR0wbJ8B83zic7rDYBsO2eLSNnfPMIY',
    appId: '1:4063681274:android:8b4670fe5fbe06f81d8743',
    messagingSenderId: '4063681274',
    projectId: 'iumopedsafe',
    databaseURL: 'https://iumopedsafe-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iumopedsafe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnaPcTEGrZ4nk44Otu4yqGniNgU3zXTdo',
    appId: '1:4063681274:ios:872da963098683dd1d8743',
    messagingSenderId: '4063681274',
    projectId: 'iumopedsafe',
    databaseURL: 'https://iumopedsafe-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iumopedsafe.appspot.com',
    iosBundleId: 'iu.mopedsafe.com.mopedsafe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnaPcTEGrZ4nk44Otu4yqGniNgU3zXTdo',
    appId: '1:4063681274:ios:6507127823f19ef51d8743',
    messagingSenderId: '4063681274',
    projectId: 'iumopedsafe',
    databaseURL: 'https://iumopedsafe-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iumopedsafe.appspot.com',
    iosBundleId: 'iu.mopedsafe.com.mopedsafe.RunnerTests',
  );
}
